name: Deploy Vite React to AWS EC2

on:
  push:
    branches:
      - main

env:
  SERVER_USER: ec2-user
  SERVER_IP: 13.210.154.160
  PROJECT_NAME: secret-test
  PROJECT_BASE_DIR: /var/www

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    # - name: Run Tests
      # run: npm test

    - name: Create .env File
      run: |
        echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env
    
    - name: Build Project
      run: npm run build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_NEWKEY }}

    - name: Prepare Target Directory
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} "
          sudo mkdir -p ${{ env.PROJECT_BASE_DIR }}/${{ env.PROJECT_NAME }}/dist &&
          sudo chown -R ${{ env.SERVER_USER }}:${{ env.SERVER_USER }} ${{ env.PROJECT_BASE_DIR }}/${{ env.PROJECT_NAME }}
        "

    - name: Deploy Static Files
      run: |
        rsync -avz --delete-after \
        -e "ssh -o StrictHostKeyChecking=no" \
        --exclude '.git' \
        ./dist/ ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:${{ env.PROJECT_BASE_DIR }}/${{ env.PROJECT_NAME }}/dist/

    - name: Change Ownership to Nginx
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} "
          sudo chown -R nginx:nginx ${{ env.PROJECT_BASE_DIR }}/${{ env.PROJECT_NAME }}
        "

    - name: Reload Nginx
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} "
          sudo systemctl reload nginx
        "
